# ---------------------------------------------------
# Otus HomeTask № 35
# Copyleft (c) by Aleksander Petrovskii aka petr0vsk
# 04-26-2021
# ----------------------------------------------------

name: Test-And-Deploy
env:
  APPLICATION_NAME   : "OtusHomeTask35"
  DEPLOY_PACKAGE_NAME: "Taskmanager-deploy-ver-${{ github.sha }}"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains test pipeline`s
  tests:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setup python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
           
      - name: Run a one-line test
        run:  python manage.py test
          

         
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [tests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line deploy
        run: echo Deploy complete!
    
        

      
